# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/cons.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_0/design_1_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c} -quiet] -quiet

# IP: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] -quiet

# IP: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_g_inst_0 || ORIG_REF_NAME==bd_f60c_g_inst_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/design_1_mMPU_Controller_AXIS_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mMPU_Controller_AXIS_1_0 || ORIG_REF_NAME==design_1_mMPU_Controller_AXIS_1_0} -quiet] -quiet

# IP: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_0/FIFO_Out_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_0 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_0} -quiet] -quiet

# IP: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_3/FIFO_Out_fifo_generator_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_3 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_3} -quiet] -quiet

# IP: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_4/FIFO_Out_fifo_generator_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_4 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_4} -quiet] -quiet

# IP: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_5/FIFO_Out_fifo_generator_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_5 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_5} -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_0/FIFO_Out_fifo_generator_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_0 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_3/FIFO_Out_fifo_generator_0_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_3 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_4/FIFO_Out_fifo_generator_0_4.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_4 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_fifo_generator_0_5/FIFO_Out_fifo_generator_0_5.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_Out_fifo_generator_0_5 || ORIG_REF_NAME==FIFO_Out_fifo_generator_0_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/ip/design_1_mMPU_Controller_AXIS_1_0/src/FIFO_Out_ooc.xdc

# XDC: C:/Users/LAB/Documents/Vivado_Projects/mMPU_System_Design/mMPU_System_Design.gen/sources_1/bd/design_1/design_1_ooc.xdc
